In [34]:
# BREAST CANCER DETECTION WITH LOGISTICS REGRESTIoN
# import libraries
import numpy as np
import sklearn.datasets

# getting  the dataset
breast_cancer = sklearn.datasets.load_breast_cancer()
print(breast_cancer) # dataset contain all the value from the test there is that target 






{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [35]:
X = breast_cancer.data
Y = breast_cancer.target
print(X)
print(Y)



[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [36]:
print(X.shape, Y.shape) # we are going to check how many data instance there
 # we are going to check how many data instance there
# we can check how many instances there 30 means 30 falllen we will be using
# now  we have need to import pandas datasets
#(569, 30) (569,) 30 meas 30 fallen we will be using 
# we can check how many instances there 30 means 30 falllen we will be using
# now  we have need to import pandas datasets
# ON THE BASIS OF 30 FEATURE WE WILL USE THAT
# IMPORT DATA TO PANDAS FRAMES
# NOW WE NEED TO IMPORT THE DATA INTO PANDAS DATA FRAMES
# WE NEED TO IMPORT THE DATA IN INTO PANDAS DATA FRAMES THE DATA FRAMES ARE USED IN OREDER TO MANIPULATE DATA INTO  FRAMES
# DO SOME OPERATION ON IT


(569, 30) (569,)


In [37]:
# NOW WE NEED TO IMPORT THE DATA SET INTO THE PANDAS DATASET
# SO PANDAS DATA FRAMES ARE VERY  USEFUL IN ORDER TO STORE THE DATA FRAMES
import pandas as pd 
data = pd.DataFrame(breast_cancer.data, columns = breast_cancer.feature_names) # panda is used for data frames


In [40]:
data['class'] = breast_cancer.target # the class  represent the label that is 0 and at all
data.head()


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [41]:
from operator import index
# now we will  see how many example for benigan and how many for maligan
print(data['class'].value_counts())
# HOW MANY DATA FOR BENIGAN AND HOW MANY FOR MALIGAN
# NOW LET'S UNDERSATND WHAT IS 0 AND WHAT IS 1
# NOW YOU SEE THE TARGET NAME IS SPECIFIED 
# NOW YOU HAVE TO UNDERSTAND THE BENIGAN AND MALIGAN STATE
# now go ahead and print how many data and value ther
# now we have to see how many data for benigan and how many data for  maligan

# # no we got that 1 is for 
print(breast_cancer.target_names)
data.head()
# now class 0 is for malingat and class 0 is for 1 is for benigan
a = ['malignant' 'benign'] # now there is 212 cases for maligant and 357 for 357 for maligant 
print(breast_cancer.target_names)
# so you can see the target name is specified
#  so you can see the target name is specified that's why we are using  target name
# now we need to finf the mean the mean value 
# you can see for class 0 is for maligan and class 1 is maligant
# now you can see the value resides
data.groupby('class').mean()
# now we have to find the mean value
# you can see the class 0 is for maligan and class 0 is for benigan
# so thes are the value of self randian
 # the values are less for beningan state
 # in order to classify benigan and maligan state
# important factor you need to come there


1    357
0    212
Name: class, dtype: int64
['malignant' 'benign']
['malignant' 'benign']


mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

# 0 - is for maligant and
## 1 - is for benigan

# Now we are going to train and test split the data

In [46]:
from sklearn.model_selection import train_test_split
X_train,X_train,Y_train,Y_test = train_test_split(X,Y)
print(Y.shape,Y_train.shape,Y_test.shape)

(569,) (426,) (143,)


In [47]:
# we only needed the 10 percentage of the data_test.shape) 
# i needed 10 percentge of the data let specified to work with it
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.1)
# point 0.1 represent the 10 percentage of the data because i needed the 10  percetage of my data
print(Y.shape,Y_train.shape, Y_test.shape)
# SO WE TAKED 10 PERCENTAGE OF OUR TESTING DATA WHICH IS 57
print(Y.mean(),Y_train.mean(), Y_test.mean())
# the mean is same for given data  training data and testing data



(569,) (512,) (57,)
0.6274165202108963 0.61328125 0.7543859649122807


In [48]:
print(Y.mean(),Y_train.mean(), Y_test.mean())
# the mean is same for given data   there is you can see the quitest difference training data and testing data



0.6274165202108963 0.61328125 0.7543859649122807


In [49]:
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.1, stratify=Y)
# WE are going to startify based on 0 or 1 into equal part startify is to split the data correctly
# for correct distribution of data
print(Y.mean(),Y_train.mean(),Y_test.mean())

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1, random_state=1)
#random_state --> random state is specific split of data each random value has of random_state split the data differently
# there is 30 poples takes default for each
# the random_state is random number generator it may be an

print(X_train.mean(),X_test.mean(),X.mean())
print(X_train)


0.6274165202108963 0.626953125 0.631578947368421
61.8522373819401 62.23631195847954 61.890712339519624
[[1.881e+01 1.998e+01 1.209e+02 ... 1.294e-01 2.567e-01 5.737e-02]
 [1.366e+01 1.515e+01 8.827e+01 ... 1.054e-01 3.387e-01 9.638e-02]
 [1.026e+01 1.658e+01 6.585e+01 ... 8.333e-02 2.691e-01 9.479e-02]
 ...
 [1.720e+01 2.452e+01 1.142e+02 ... 1.899e-01 3.313e-01 1.339e-01]
 [1.403e+01 2.125e+01 8.979e+01 ... 7.963e-02 2.226e-01 7.617e-02]
 [1.303e+01 1.842e+01 8.261e+01 ... 5.013e-02 1.987e-01 6.169e-02]]


Logistic Regression - logistic regression is supervised learning algorithm . it
is best for binary class classsification

In [50]:
# let's import import Logistic Regression from sklearn
from sklearn.linear_model import LogisticRegression
# we can develope the logistic regression from scrach but it's time consuming
classifier = LogisticRegression() # loading the logistic regression model to variable classifier
# training the model on training data
# wheater it's malingan or benigan 
classifier.fit(X_train, Y_train)
# my model is trained with the training data we had given
# now let's go ahead and check the evaluation of our model


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

Evaluation of the model
### EVALUATION OF OUR MODEL

In [51]:
# import accuracy_score
# WE NEED TO IMPORT ACCURACY SCORE FROM SKLEARN
from sklearn.metrics import accuracy_score
# let's see how model works on test data let's see how model works on test data
# prediction on traninig data
prediction_on_training_data = classifier.predict(X_train)
accuracy_on_trainig_data = accuracy_score(Y_train, prediction_on_training_data)
print('Accuracy on trainig data :', accuracy_on_trainig_data)
# now the accuracy is 95 percentage let's go ahead and see


# we need to import accuracy score from sklearn
# so this is the evaluation method for the 
# now logistic regresion model 
# import accuracy score
# let's see how the model works on training data
# let's see on how model works on test data

# let's make the prediction on test data



Accuracy on trainig data : 0.943359375


In [52]:
# prediciton on test_data
prediction_on_test_data = classifier.predict(X_test)
accuracy_on_test_data = accuracy_score(Y_test,prediction_on_test_data)
print('Accuracy on test  data :', accuracy_on_test_data)
# accuracy on test data is greater than the accuracy on training data




Accuracy on test  data : 0.9824561403508771


# Detecting wheather the patient has which type of canncer benigan or maligan stage

In [58]:
input_data = (13.08,15.71,85.63,520,0.1075,0.127,0.04568,0.0311,0.1967,0.06811,0.1852,0.7477,1.383,14.67,0.004097,0.01898,0.01698,0.00649,0.01678,0.002425,14.5,20.49,96.09,630.5,0.1312,0.2776,0.189,0.07283,0.3184,0.08183)
# change the input data to numpy arrays to make prediction
input_data_as_numpy_array = np.asarray(input_data)
print(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = classifier.predict(input_data_reshaped)
print(prediction) # returns a list with 0 and 1 we have to get from the list 
# returns a list with [0] if maligant; return a list with element[1], if benign

# if 0 it's means malingant  otherwise it's benign
# 
# accutaly it's returns a list element 0 and 1 0 it means maligan if 1 it means maligan
# we have need to get 0 and 1 from this list
# if person's comes we can analyze the person is from which stage of cancer 
if (prediction[0] == 0):
  print('the breast Cancer is Malingant')
else:
  print('The breast Cacer is benigan')




(13.08, 15.71, 85.63, 520, 0.1075, 0.127, 0.04568, 0.0311, 0.1967, 0.06811, 0.1852, 0.7477, 1.383, 14.67, 0.004097, 0.01898, 0.01698, 0.00649, 0.01678, 0.002425, 14.5, 20.49, 96.09, 630.5, 0.1312, 0.2776, 0.189, 0.07283, 0.3184, 0.08183)
[1]
The breast Cacer is benigan
